CC = g++
MSDOSDIR = msdosdir.cpp BootStrapSector.cpp DirectoryEntry.cpp
TESTING = test.cpp BootStrapSector.cpp DirectoryEntry.cpp byte.cpp
FILE = samplefat.bin

test : $(TESTING)
	$(CC) -o test $(TESTING)
