CC = g++
MSDOSDIR = msdosdir.cpp BootStrapSector.cpp DirectoryEntry.cpp DirectoryListing.cpp byte.cpp
# TESTING = test.cpp BootStrapSector.cpp DirectoryEntry.cpp byte.cpp
FILE = samplefat.bin

msdosdir : $(MSDOSDIR)
	$(CC) -o msdosdir $(MSDOSDIR)
